### ISSUE TITLE
comma in entity names causes read_data_entity_names to return extra columns

### ISSUE THREAD

**Issue by atn38** [ropensci/EDIutils#38]
`EDIutils::read_data_entity_name("knb-lter-ble.12.1")` returns

![image](https://user-images.githubusercontent.com/42045942/167987822-a06dda9d-2d55-48de-904c-1e0a3b4caea3.png)

See the extra unnamed column. The entity name as listed in EML is "Sediment pigment data, personnel list". 

I figure this is not particularly EDIutils' fault but perhaps the PASTA API? Reporting here because EDIutils is what I was using.

**Comment by clnsmth** [comment]
Thanks for reporting this issue @atn38!

As you've figured, this issue is related to the PASTA API specifically the use of commas to delimit data entity identifiers from data entity names in the response object of the Read Data Entity Names method.

I'll implement a fix here for EDIutils and also raise this at https://github.com/PASTAplus/PASTA.
