### ISSUE TITLE
add vignette to get the newest version of a dataset

### ISSUE THREAD

**Issue by cgries** [ropensci/EDIutils#46]
Hilary Dugan suggested to write a vignette the describes the filter="newest" functionality in some functions.

**Comment by clnsmth** [comment]
Thanks for relaying this suggestion @cgries. 

Hi @hdugan! Did you have anything specific in mind?

**Comment by hdugan** [comment]
So this came up because Corinna told me about the functionality and I had no idea it existed (and it's great). However, reading through the vignette and examples it still took me a a bit of time to figure out how to implement it. 

Here's my code where I pull the most recent data for a shiny app 
https://github.com/hdugan/NTLviewer/blob/master/server.R

I was thinking a simple example along those lines would be helpful for someone trying to do the same thing.

**Comment by clnsmth** [comment]
Thanks for the inspiration, @hdugan.

I completely agree that EDIutils is currently putting too much burden on users to discover and make sense of this feature.

To address this issue:

1. **_Prominent Example in README_**: We could place a relevant example front and center in the package [README](https://docs.ropensci.org/EDIutils/index.html). This would provide users with a quick and clear understanding of how to use this feature without diving into details.
2. **_In-Depth Explanation in Vignette_**: Additionally, we can include the same example in the [Search and Access](https://docs.ropensci.org/EDIutils/articles/search_and_access.html) vignette, where there's more space to explain the nuances of data package versioning, such as why data entity identifiers cannot be reliably reused across versions (e.g., because they almost always change).

Thoughts?

**Comment by hdugan** [comment]
I think both sound great, although I'm not sure how common this use-case is. If you all deem it rare, in that most people know what version they want, it could just be in the vignette.

**Comment by clnsmth** [comment]
Hi @hdugan. I've added a section to the 'Search and Access' vignette to demonstrate this. Would you mind taking a look when you have a minute?

https://github.com/ropensci/EDIutils/pull/50/commits/41c63995a0660539bbc81651a6721b6ea7e13ede

Does it make sense?

**Comment by hdugan** [comment]
Yeah looks great, and good considerations that you've added.
